### ISSUE TITLE
random crashes on RPi

### ISSUE THREAD

**Issue by fpiesik** [reduzent/netpd#4]
Hi, I've installed netpd on a raspberry pi 2 and it works well for some minutes, but then it suddenly crashes the whole pd instance. I can't figure out why or when this happens. Sometimes it plays for about 10 minutes without any issues. Sometimes it crashes almost directly after I started it.

**Comment by thisconnect** [comment]
:eyes:

**Comment by reduzent** [comment]
It would be interesting to know whether it happens in Pd or in one of the externals.  You can run Pd inside the GNU debugger like this:

gdb -ex run --args pd -noprefs -nrt -stderr -alsa -channels 2  -open chat.pd

When it crashes, you type 'backtrace', it'll print a  backtrace of the crash. You may send me the result.

I also suspect some race condition to occur with one of the threaded external classes (probably iemnet?). I once experienced sudden crashes on another computer and I think I got rid of them by sticking the Pd process to one core with something like:

taskset -p 0x0000001 24251

where 24251 is the PID of pd.

Hope that helps.

**Comment by fpiesik** [comment]
After some hours of testing with the taskset command, I'm pretty shure that solved the problem. So I'll close this issue - thanks!

**Comment by reduzent** [comment]
Thanks for testing and confirming. This means there is still an issue, but most likely not with netpd itself, but with an external that netpd uses. Since it occurs only when threads are spread across cores (as opposed to run on the same core), it can be narrowed down to externals that use threading. I think of the externals that netpd uses only iemnet employs threading.
